name: adminer
icon: adminer
type: service
title: Adminer
scalable: false

env:
- name: ADMINER_PLUGINS
  value: 'tables-filter edit-textarea'

options:
- version: '6'
  tag: '6-6.1.0'
  default: true

endpoints:
- name: adminer
  ports:
  - name: http
    number: 80
    protocol: http

labels:
- adminer
- database-admin

links:
- name: db
  title: Database
  required: true
  env:
  - name: ADMINER_DEFAULT_DB_DRIVER
    value: '{{link.database.driver}}'
  - name: ADMINER_DEFAULT_DB_HOST
    value: '{{link.database.host}}:{{link.database.port}}'
  - name: ADMINER_DEFAULT_DB_NAME
    value: '{{link.database.db.name}}'
  selectors:
  - type: db
    labels:
    - mariadb
  - type: db
    labels:
    - mysql
  - type: db
    labels:
    - postgres

deployment:
  strategy: recreate
  minReady: 10s
  progressDeadline: 15m
  shutdownGracePeriod: 30s

helm:
  name: wodby
  source: oci://registry-1.docker.io/wodby/adminer
  chart: oci://registry-1.docker.io/wodby/adminer
  version: 0.3.1
  valueMappings:
    replicas: replicaCount
    fullnameOverride: fullnameOverride
    serviceAccountName: serviceAccount.name
    serviceAccountCreate: serviceAccount.create

workloads:
- name: main
  selector:
    matchLabels:
      app.kubernetes.io/instance: '{{helm.release}}'
  kind: deployment
  primary: true
  helm:
    labels: podLabels
    annotations: podAnnotations
    volumes: extraVolumes
  containers:
  - name: adminer
    image: wodby/adminer
    helm:
      resources: resources
      env: envVars
      mounts: extraVolumeMounts
